# Generated by Django 4.2.21 on 2025-06-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arquivos", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="blacklist",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="blacklist",
            name="numero",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.RemoveField(
            model_name="blacklist",
            name="usuario",
        ),
    ]
