# Generated by Django 4.2.21 on 2025-06-06 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0002_alter_blacklist_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='numero',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
