# Generated by Django 4.2.21 on 2025-06-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0004_empresa_perfilusuario_blacklist_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
