# Generated by Django 4.2.21 on 2025-06-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0005_blacklistglobal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='empresa',
        ),
        migrations.CreateModel(
            name='EmpresaBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquivos.blacklist')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arquivos.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'blacklist')},
            },
        ),
    ]
