# Generated by Django 4.2.21 on 2025-06-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0006_remove_blacklist_empresa_empresablacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
