# Generated by Django 4.2.21 on 2025-06-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0007_perfilusuario_is_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadarquivo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arquivos.empresa'),
            preserve_default=False,
        ),
    ]
