# Generated by Django 4.2.21 on 2025-06-12 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arquivos', '0008_alter_uploadarquivo_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresablacklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
